# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-08-21 05:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multicloud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createec2instance',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multicloud.GetVpcs'),  # noqa
        ),
        migrations.AlterField(
            model_name='createec2instance',
            name='subnet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multicloud.GetSubnets'),  # noqa
        ),
    ]
